jaguar:
  host: 0.0.0.0
  ppport: 18090
  pushs:
   

logging:
  level: debug
  path: logs
spring:
  redis:
    database: 9
    host: "201.201.201.173"
    port: 6379
    timeout: 5000
    pool:
      max-active: 64
      max-idle: 8
      max-wait: -1
  data:
    mongodb:
      database: Jaguar
      host: 201.201.201.174
      port: 27017

mybatis:
  mapper-locations:
    - mapper/*.xml


