jaguar:
  host: 0.0.0.0
  port: 18090
  pushs:
    - systemId: 4
      apns:
        topic: guotong.GtOilStorage
        cerpath: apns/guotong.p12
        cerpass: 123456
      androids:
        leancloud:
          action: com.gt.app.gtecard.PUSH_RECEIVER
          appId: uqJGEgRR5sblpLEQTNzLHsMP-gzGzoHsz
          appKey: 7WsfQY6CM52MhX2BeF9XcOyN
          masterKey: LlCowinwbCplX4lxc4QCIl26
    - systemId: 5
      apns:
        topic: cn.ccc680.TVModule
        cerpath: apns/caipiao.p12
        cerpass: 654321
      androids:
        leancloud:
          action: com.ccc680.lottery.PUSH_RECEIVER
          appId: iR8Gw7PIKBtglDwiJBGeBXgz-gzGzoHsz
          appKey: VUmTpmQgqT2lcALQcdBbNc1f
          masterKey: h89SUasqidddXG9nUwmrJ6YB

logging:
  level: debug
  path: logs
spring:
  redis:
    database: 9
    host: "201.201.201.173"
    port: 6379
    timeout: 5000
    pool:
      max-active: 64
      max-idle: 8
      max-wait: -1
  data:
    mongodb:
      database: Jaguar
      host: 201.201.201.174
      port: 27017




